### ISSUE TITLE
Creare un controllo path

### ISSUE THREAD

**Issue by algebrato** [gruffoc/CamView#1]
Se l'acquisizione viene avviata con una directory non esistente o con un parametro non settato, il programma deve restituire un messaggio d'errore, per esempio attraverso una:

`QMessageBox::information(0,"Open File", "ERRORE!\n Impossibile trovare la path indicata ");`
oppure

`QMessageBox::information(0,"Open File", "ERRORE!\n FrameRate non settato - indicare un FrameRate ");`

**Comment by claudriel** [comment]
Completata
